// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TestScripts.SingleOrder;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Step_SingleOrder</b><br>
 * Generated     : <b>2021/01/14 4:00:07 pm</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  January 14, 2021
 * @author msadmin
 */
public abstract class Step_SingleOrderHelper extends RationalTestScript
{
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Ok() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Ok"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Ok(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Ok"), anchor, flags);
	}
	
	/**
	 * Save: with default state.
	 *		.text : Save
	 * 		.class : .Pushbutton
	 * 		.name : Save
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Save() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Save"));
	}
	/**
	 * Save: with specific test context and state.
	 *		.text : Save
	 * 		.class : .Pushbutton
	 * 		.name : Save
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Save(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Save"), anchor, flags);
	}
	
	/**
	 * Yes: with default state.
	 *		.text : Yes
	 * 		.class : .Pushbutton
	 * 		.name : Yes
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Yes() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Yes"));
	}
	/**
	 * Yes: with specific test context and state.
	 *		.text : Yes
	 * 		.class : .Pushbutton
	 * 		.name : Yes
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Yes(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Yes"), anchor, flags);
	}
	
	/**
	 * ComboBox: with default state.
	 *		.text : File name:
	 * 		.class : ComboBox
	 * 		.name : File name:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject Cbo_FileName() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("Cbo_FileName"));
	}
	/**
	 * ComboBox: with specific test context and state.
	 *		.text : File name:
	 * 		.class : ComboBox
	 * 		.name : File name:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject Cbo_FileName(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("Cbo_FileName"), anchor, flags);
	}
	
	/**
	 * ComboBox: with default state.
	 *		.text : Product :
	 * 		.class : ComboBox
	 * 		.name : Product :
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject Cbo_Product() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("Cbo_Product"));
	}
	/**
	 * ComboBox: with specific test context and state.
	 *		.text : Product :
	 * 		.class : ComboBox
	 * 		.name : Product :
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject Cbo_Product(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("Cbo_Product"), anchor, flags);
	}
	
	/**
	 * ComboBox: with default state.
	 *		.text : Save in:
	 * 		.class : ComboBox
	 * 		.name : Save in:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject Cbo_SaveIn() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("Cbo_SaveIn"));
	}
	/**
	 * ComboBox: with specific test context and state.
	 *		.text : Save in:
	 * 		.class : ComboBox
	 * 		.name : Save in:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject Cbo_SaveIn(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("Cbo_SaveIn"), anchor, flags);
	}
	
	/**
	 * _1: with default state.
	 *		.text : Quantity:
	 * 		.class : Edit
	 * 		.name : Quantity:
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject Cbo_Type() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Cbo_Type"));
	}
	/**
	 * _1: with specific test context and state.
	 *		.text : Quantity:
	 * 		.class : Edit
	 * 		.name : Quantity:
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject Cbo_Type(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Cbo_Type"), anchor, flags);
	}
	
	/**
	 * Application: with default state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject Menu_File() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menu_File"));
	}
	/**
	 * Application: with specific test context and state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject Menu_File(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menu_File"), anchor, flags);
	}
	
	/**
	 * Application: with default state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject Menu_Orders() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menu_Orders"));
	}
	/**
	 * Application: with specific test context and state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject Menu_Orders(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menu_Orders"), anchor, flags);
	}
	
	/**
	 * Edit: with default state.
	 *		.text : Card Nr:
	 * 		.class : Edit
	 * 		.name : Card Nr:
	 * 		.classIndex : 9
	 */
	protected TextGuiTestObject Txt_Card() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_Card"));
	}
	/**
	 * Edit: with specific test context and state.
	 *		.text : Card Nr:
	 * 		.class : Edit
	 * 		.name : Card Nr:
	 * 		.classIndex : 9
	 */
	protected TextGuiTestObject Txt_Card(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_Card"), anchor, flags);
	}
	
	/**
	 * Edit: with default state.
	 *		.text : City:
	 * 		.class : Edit
	 * 		.name : City:
	 * 		.classIndex : 6
	 */
	protected TextGuiTestObject Txt_City() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_City"));
	}
	/**
	 * Edit: with specific test context and state.
	 *		.text : City:
	 * 		.class : Edit
	 * 		.name : City:
	 * 		.classIndex : 6
	 */
	protected TextGuiTestObject Txt_City(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_City"), anchor, flags);
	}
	
	/**
	 * Edit: with default state.
	 *		.text : Customer Name:
	 * 		.class : Edit
	 * 		.name : Customer Name:
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject Txt_CustomerName() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_CustomerName"));
	}
	/**
	 * Edit: with specific test context and state.
	 *		.text : Customer Name:
	 * 		.class : Edit
	 * 		.name : Customer Name:
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject Txt_CustomerName(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_CustomerName"), anchor, flags);
	}
	
	/**
	 * Save: with default state.
	 *		.text : Save
	 * 		.class : #32770
	 * 		.processName : Orders.exe
	 * 		.name : Save
	 */
	protected TopLevelSubitemTestObject Txt_FileName() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Txt_FileName"));
	}
	/**
	 * Save: with specific test context and state.
	 *		.text : Save
	 * 		.class : #32770
	 * 		.processName : Orders.exe
	 * 		.name : Save
	 */
	protected TopLevelSubitemTestObject Txt_FileName(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Txt_FileName"), anchor, flags);
	}
	
	/**
	 * Edit: with default state.
	 *		.text : State:
	 * 		.class : Edit
	 * 		.name : State:
	 * 		.classIndex : 7
	 */
	protected TextGuiTestObject Txt_State() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_State"));
	}
	/**
	 * Edit: with specific test context and state.
	 *		.text : State:
	 * 		.class : Edit
	 * 		.name : State:
	 * 		.classIndex : 7
	 */
	protected TextGuiTestObject Txt_State(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_State"), anchor, flags);
	}
	
	/**
	 * Edit: with default state.
	 *		.text : Street:
	 * 		.class : Edit
	 * 		.name : Street:
	 * 		.classIndex : 5
	 */
	protected TextGuiTestObject Txt_Street() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_Street"));
	}
	/**
	 * Edit: with specific test context and state.
	 *		.text : Street:
	 * 		.class : Edit
	 * 		.name : Street:
	 * 		.classIndex : 5
	 */
	protected TextGuiTestObject Txt_Street(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_Street"), anchor, flags);
	}
	
	/**
	 * Edit: with default state.
	 *		.text : Zip:
	 * 		.class : Edit
	 * 		.name : Zip:
	 * 		.classIndex : 8
	 */
	protected TextGuiTestObject Txt_Zip() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_Zip"));
	}
	/**
	 * Edit: with specific test context and state.
	 *		.text : Zip:
	 * 		.class : Edit
	 * 		.name : Zip:
	 * 		.classIndex : 8
	 */
	protected TextGuiTestObject Txt_Zip(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_Zip"), anchor, flags);
	}
	
	/**
	 * NewOrder: with default state.
	 *		.text : New order
	 * 		.class : #32770
	 * 		.processName : Orders.exe
	 * 		.name : New order
	 */
	protected TopLevelSubitemTestObject Win_NewOrder() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Win_NewOrder"));
	}
	/**
	 * NewOrder: with specific test context and state.
	 *		.text : New order
	 * 		.class : #32770
	 * 		.processName : Orders.exe
	 * 		.name : New order
	 */
	protected TopLevelSubitemTestObject Win_NewOrder(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Win_NewOrder"), anchor, flags);
	}
	
	/**
	 * PlacedOrdersTblOrders: with default state.
	 *		.text : PlacedOrders.tbl - Orders
	 * 		.class : Afx:00400000:b:00010003:00000006:0034085B
	 * 		.processName : Orders.exe
	 * 		.name : PlacedOrders.tbl - Orders
	 */
	protected TopLevelSubitemTestObject Wnd_MainTable() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Wnd_MainTable"));
	}
	/**
	 * PlacedOrdersTblOrders: with specific test context and state.
	 *		.text : PlacedOrders.tbl - Orders
	 * 		.class : Afx:00400000:b:00010003:00000006:0034085B
	 * 		.processName : Orders.exe
	 * 		.name : PlacedOrders.tbl - Orders
	 */
	protected TopLevelSubitemTestObject Wnd_MainTable(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Wnd_MainTable"), anchor, flags);
	}
	
	/**
	 * SysDateTimePick32: with default state.
	 *		.text : Expiration Date:
	 * 		.class : SysDateTimePick32
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject sysDateTimePick32calendar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("sysDateTimePick32calendar"));
	}
	/**
	 * SysDateTimePick32: with specific test context and state.
	 *		.text : Expiration Date:
	 * 		.class : SysDateTimePick32
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject sysDateTimePick32calendar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("sysDateTimePick32calendar"), anchor, flags);
	}
	
	/**
	 * SysDateTimePick32: with default state.
	 *		.text : Date:
	 * 		.class : SysDateTimePick32
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject sysDateTimePick32calendar2() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("sysDateTimePick32calendar2"));
	}
	/**
	 * SysDateTimePick32: with specific test context and state.
	 *		.text : Date:
	 * 		.class : SysDateTimePick32
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject sysDateTimePick32calendar2(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("sysDateTimePick32calendar2"), anchor, flags);
	}
	
	/**
	 * SysMonthCal32: with default state.
	 *		.class : SysMonthCal32
	 * 		.name : 
	 * 		.classIndex : null
	 */
	protected TopLevelSubitemTestObject sysMonthCal32calendar() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("sysMonthCal32calendar"));
	}
	/**
	 * SysMonthCal32: with specific test context and state.
	 *		.class : SysMonthCal32
	 * 		.name : 
	 * 		.classIndex : null
	 */
	protected TopLevelSubitemTestObject sysMonthCal32calendar(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("sysMonthCal32calendar"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point manual1 object in the SUT.
	 */
	protected IFtVerificationPoint manual1VP() 
	{
		return vp("manual1");
	}
	protected IFtVerificationPoint manual1VP(TestObject anchor)
	{
		return vp("manual1", anchor);
	}
	
	/**
	 * Locate and return the verification point MyMoney object in the SUT.
	 */
	protected IFtVerificationPoint MyMoneyVP() 
	{
		return vp("MyMoney");
	}
	protected IFtVerificationPoint MyMoneyVP(TestObject anchor)
	{
		return vp("MyMoney", anchor);
	}
	
	

	protected Step_SingleOrderHelper()
	{
		setScriptName("TestScripts.SingleOrder.Step_SingleOrder");
	}
	
}

