// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TestScripts.Steps.Step_Save;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>SaveOrder</b><br>
 * Generated     : <b>2021/01/18 12:41:25 pm</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  January 18, 2021
 * @author msadmin
 */
public abstract class SaveOrderHelper extends RationalTestScript
{
	/**
	 * Save: with default state.
	 *		.text : Save
	 * 		.class : .Pushbutton
	 * 		.name : Save
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Save() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Save"));
	}
	/**
	 * Save: with specific test context and state.
	 *		.text : Save
	 * 		.class : .Pushbutton
	 * 		.name : Save
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Save(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Save"), anchor, flags);
	}
	
	/**
	 * Yes: with default state.
	 *		.text : Yes
	 * 		.class : .Pushbutton
	 * 		.name : Yes
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Yes() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Yes"));
	}
	/**
	 * Yes: with specific test context and state.
	 *		.text : Yes
	 * 		.class : .Pushbutton
	 * 		.name : Yes
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Yes(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Yes"), anchor, flags);
	}
	
	/**
	 * ComboBox: with default state.
	 *		.text : File name:
	 * 		.class : ComboBox
	 * 		.name : File name:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject Cbo_SaveIn() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("Cbo_SaveIn"));
	}
	/**
	 * ComboBox: with specific test context and state.
	 *		.text : File name:
	 * 		.class : ComboBox
	 * 		.name : File name:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject Cbo_SaveIn(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("Cbo_SaveIn"), anchor, flags);
	}
	
	/**
	 * Application: with default state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject Menu_File() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menu_File"));
	}
	/**
	 * Application: with specific test context and state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject Menu_File(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Menu_File"), anchor, flags);
	}
	
	/**
	 * Save: with default state.
	 *		.text : Save
	 * 		.class : #32770
	 * 		.processName : Orders.exe
	 * 		.name : Save
	 */
	protected TopLevelSubitemTestObject Txt_FileName() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Txt_FileName"));
	}
	/**
	 * Save: with specific test context and state.
	 *		.text : Save
	 * 		.class : #32770
	 * 		.processName : Orders.exe
	 * 		.name : Save
	 */
	protected TopLevelSubitemTestObject Txt_FileName(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Txt_FileName"), anchor, flags);
	}
	
	/**
	 * PlacedOrdersTblOrders: with default state.
	 *		.text : PlacedOrders.tbl - Orders
	 * 		.class : Afx:00400000:b:00010003:00000006:314A0B13
	 * 		.processName : Orders.exe
	 * 		.name : PlacedOrders.tbl - Orders
	 */
	protected TopLevelSubitemTestObject Wnd_MainTable() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Wnd_MainTable"));
	}
	/**
	 * PlacedOrdersTblOrders: with specific test context and state.
	 *		.text : PlacedOrders.tbl - Orders
	 * 		.class : Afx:00400000:b:00010003:00000006:314A0B13
	 * 		.processName : Orders.exe
	 * 		.name : PlacedOrders.tbl - Orders
	 */
	protected TopLevelSubitemTestObject Wnd_MainTable(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Wnd_MainTable"), anchor, flags);
	}
	
	

	protected SaveOrderHelper()
	{
		setScriptName("TestScripts.Steps.Step_Save.SaveOrder");
	}
	
}

