// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TestScripts.DeleteOrders;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Step_DeleteOrder</b><br>
 * Generated     : <b>2021/01/14 4:16:41 pm</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  January 14, 2021
 * @author msadmin
 */
public abstract class Step_DeleteOrderHelper extends RationalTestScript
{
	/**
	 * ComboBox: with default state.
	 *		.text : File name:
	 * 		.class : ComboBox
	 * 		.name : File name:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject Txt_FileName() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("Txt_FileName"));
	}
	/**
	 * ComboBox: with specific test context and state.
	 *		.text : File name:
	 * 		.class : ComboBox
	 * 		.name : File name:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject Txt_FileName(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("Txt_FileName"), anchor, flags);
	}
	
	/**
	 * Application: with default state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject applicationmenuBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("applicationmenuBar"));
	}
	/**
	 * Application: with specific test context and state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject applicationmenuBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("applicationmenuBar"), anchor, flags);
	}
	
	/**
	 * ComboBox: with default state.
	 *		.text : Look in:
	 * 		.class : ComboBox
	 * 		.name : Look in:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject comboBoxcomboBox() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("comboBoxcomboBox"));
	}
	/**
	 * ComboBox: with specific test context and state.
	 *		.text : Look in:
	 * 		.class : ComboBox
	 * 		.name : Look in:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject comboBoxcomboBox(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("comboBoxcomboBox"), anchor, flags);
	}
	
	/**
	 * ComboBox: with default state.
	 *		.text : File name:
	 * 		.class : ComboBox
	 * 		.name : File name:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject comboBoxcomboBox2() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("comboBoxcomboBox2"));
	}
	/**
	 * ComboBox: with specific test context and state.
	 *		.text : File name:
	 * 		.class : ComboBox
	 * 		.name : File name:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject comboBoxcomboBox2(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("comboBoxcomboBox2"), anchor, flags);
	}
	
	/**
	 * Context: with default state.
	 *		.text : Context
	 * 		.class : .Menupopup
	 * 		.name : Context
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject contextpopupMenu() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("contextpopupMenu"));
	}
	/**
	 * Context: with specific test context and state.
	 *		.text : Context
	 * 		.class : .Menupopup
	 * 		.name : Context
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject contextpopupMenu(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("contextpopupMenu"), anchor, flags);
	}
	
	/**
	 * FolderView: with default state.
	 *		.text : Folder View
	 * 		.class : SysListView32
	 * 		.name : Folder View
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject folderViewtable() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("folderViewtable"));
	}
	/**
	 * FolderView: with specific test context and state.
	 *		.text : Folder View
	 * 		.class : SysListView32
	 * 		.name : Folder View
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject folderViewtable(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("folderViewtable"), anchor, flags);
	}
	
	/**
	 * Open: with default state.
	 *		.text : Open
	 * 		.class : .Pushbutton
	 * 		.name : Open
	 * 		.classIndex : 0
	 */
	protected GuiTestObject openbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("openbutton"));
	}
	/**
	 * Open: with specific test context and state.
	 *		.text : Open
	 * 		.class : .Pushbutton
	 * 		.name : Open
	 * 		.classIndex : 0
	 */
	protected GuiTestObject openbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("openbutton"), anchor, flags);
	}
	
	/**
	 * PlacedOrders1TblOrders: with default state.
	 *		.text : PlacedOrders1.tbl - Orders
	 * 		.class : Afx:00400000:b:00010003:00000006:098308FB
	 * 		.processName : Orders.exe
	 * 		.name : PlacedOrders1.tbl - Orders
	 */
	protected TopLevelSubitemTestObject placedOrders1TblOrderswindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("placedOrders1TblOrderswindow"));
	}
	/**
	 * PlacedOrders1TblOrders: with specific test context and state.
	 *		.text : PlacedOrders1.tbl - Orders
	 * 		.class : Afx:00400000:b:00010003:00000006:098308FB
	 * 		.processName : Orders.exe
	 * 		.name : PlacedOrders1.tbl - Orders
	 */
	protected TopLevelSubitemTestObject placedOrders1TblOrderswindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("placedOrders1TblOrderswindow"), anchor, flags);
	}
	
	/**
	 * SysListView32: with default state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject sysListView32table() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("sysListView32table"));
	}
	/**
	 * SysListView32: with specific test context and state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject sysListView32table(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("sysListView32table"), anchor, flags);
	}
	
	/**
	 * Yes: with default state.
	 *		.text : Yes
	 * 		.class : .Pushbutton
	 * 		.name : Yes
	 * 		.classIndex : 0
	 */
	protected GuiTestObject yesbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("yesbutton"));
	}
	/**
	 * Yes: with specific test context and state.
	 *		.text : Yes
	 * 		.class : .Pushbutton
	 * 		.name : Yes
	 * 		.classIndex : 0
	 */
	protected GuiTestObject yesbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("yesbutton"), anchor, flags);
	}
	
	

	protected Step_DeleteOrderHelper()
	{
		setScriptName("TestScripts.DeleteOrders.Step_DeleteOrder");
	}
	
}

