// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TestScripts.EditOrders;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>EditOrder</b><br>
 * Generated     : <b>2021/01/18 5:37:19 pm</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  January 18, 2021
 * @author msadmin
 */
public abstract class EditOrderHelper extends RationalTestScript
{
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Ok() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Ok"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Ok(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Ok"), anchor, flags);
	}
	
	/**
	 * Open: with default state.
	 *		.text : Open
	 * 		.class : .Pushbutton
	 * 		.name : Open
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Open() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Open"));
	}
	/**
	 * Open: with specific test context and state.
	 *		.text : Open
	 * 		.class : .Pushbutton
	 * 		.name : Open
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Open(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Open"), anchor, flags);
	}
	
	/**
	 * Yes: with default state.
	 *		.text : Yes
	 * 		.class : .Pushbutton
	 * 		.name : Yes
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Yes() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Yes"));
	}
	/**
	 * Yes: with specific test context and state.
	 *		.text : Yes
	 * 		.class : .Pushbutton
	 * 		.name : Yes
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Yes(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Yes"), anchor, flags);
	}
	
	/**
	 * SysListView32: with default state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject Lvw_ListViewTable() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("Lvw_ListViewTable"));
	}
	/**
	 * SysListView32: with specific test context and state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject Lvw_ListViewTable(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("Lvw_ListViewTable"), anchor, flags);
	}
	
	/**
	 * EditOrder: with default state.
	 *		.text : Edit order
	 * 		.class : #32770
	 * 		.processName : Orders.exe
	 * 		.name : Edit order
	 */
	protected TopLevelSubitemTestObject Lvw_OrderTable() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Lvw_OrderTable"));
	}
	/**
	 * EditOrder: with specific test context and state.
	 *		.text : Edit order
	 * 		.class : #32770
	 * 		.processName : Orders.exe
	 * 		.name : Edit order
	 */
	protected TopLevelSubitemTestObject Lvw_OrderTable(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Lvw_OrderTable"), anchor, flags);
	}
	
	/**
	 * Application: with default state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject MenuBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("MenuBar"));
	}
	/**
	 * Application: with specific test context and state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject MenuBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("MenuBar"), anchor, flags);
	}
	
	/**
	 * Context: with default state.
	 *		.text : Context
	 * 		.class : .Menupopup
	 * 		.name : Context
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject PopUpMenu() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("PopUpMenu"));
	}
	/**
	 * Context: with specific test context and state.
	 *		.text : Context
	 * 		.class : .Menupopup
	 * 		.name : Context
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject PopUpMenu(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("PopUpMenu"), anchor, flags);
	}
	
	/**
	 * Edit: with default state.
	 *		.text : Card Nr:
	 * 		.class : Edit
	 * 		.name : Card Nr:
	 * 		.classIndex : 9
	 */
	protected TextGuiTestObject Txt_CardNo() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_CardNo"));
	}
	/**
	 * Edit: with specific test context and state.
	 *		.text : Card Nr:
	 * 		.class : Edit
	 * 		.name : Card Nr:
	 * 		.classIndex : 9
	 */
	protected TextGuiTestObject Txt_CardNo(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_CardNo"), anchor, flags);
	}
	
	/**
	 * MatryxSoft: with default state.
	 *		.text : Customer Name:
	 * 		.class : Edit
	 * 		.name : Customer Name:
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject Txt_CustomerName() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_CustomerName"));
	}
	/**
	 * MatryxSoft: with specific test context and state.
	 *		.text : Customer Name:
	 * 		.class : Edit
	 * 		.name : Customer Name:
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject Txt_CustomerName(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Txt_CustomerName"), anchor, flags);
	}
	
	/**
	 * PlacedOrdersTblOrders: with default state.
	 *		.text : PlacedOrders.tbl - Orders
	 * 		.class : Afx:00400000:b:00010003:00000006:02730287
	 * 		.processName : Orders.exe
	 * 		.name : PlacedOrders.tbl - Orders
	 */
	protected TopLevelSubitemTestObject Wnd_Order() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Wnd_Order"));
	}
	/**
	 * PlacedOrdersTblOrders: with specific test context and state.
	 *		.text : PlacedOrders.tbl - Orders
	 * 		.class : Afx:00400000:b:00010003:00000006:02730287
	 * 		.processName : Orders.exe
	 * 		.name : PlacedOrders.tbl - Orders
	 */
	protected TopLevelSubitemTestObject Wnd_Order(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Wnd_Order"), anchor, flags);
	}
	
	/**
	 * Open: with default state.
	 *		.text : Open
	 * 		.class : #32770
	 * 		.processName : Orders.exe
	 * 		.name : Open
	 */
	protected TopLevelSubitemTestObject openwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("openwindow"));
	}
	/**
	 * Open: with specific test context and state.
	 *		.text : Open
	 * 		.class : #32770
	 * 		.processName : Orders.exe
	 * 		.name : Open
	 */
	protected TopLevelSubitemTestObject openwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("openwindow"), anchor, flags);
	}
	
	

	protected EditOrderHelper()
	{
		setScriptName("TestScripts.EditOrders.EditOrder");
	}
	
}

