// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TestScripts.Temp;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Script1</b><br>
 * Generated     : <b>2021/01/12 10:03:58 am</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  January 12, 2021
 * @author msadmin
 */
public abstract class Script1Helper extends RationalTestScript
{
	/**
	 * Application: with default state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject applicationmenuBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("applicationmenuBar"));
	}
	/**
	 * Application: with specific test context and state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject applicationmenuBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("applicationmenuBar"), anchor, flags);
	}
	
	/**
	 * Context: with default state.
	 *		.text : Context
	 * 		.class : .Menupopup
	 * 		.name : Context
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject contextpopupMenu() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("contextpopupMenu"));
	}
	/**
	 * Context: with specific test context and state.
	 *		.text : Context
	 * 		.class : .Menupopup
	 * 		.name : Context
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject contextpopupMenu(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("contextpopupMenu"), anchor, flags);
	}
	
	/**
	 * SysDateTimePick32: with default state.
	 *		.text : Date:
	 * 		.class : SysDateTimePick32
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject sysDateTimePick32calendar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("sysDateTimePick32calendar"));
	}
	/**
	 * SysDateTimePick32: with specific test context and state.
	 *		.text : Date:
	 * 		.class : SysDateTimePick32
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject sysDateTimePick32calendar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("sysDateTimePick32calendar"), anchor, flags);
	}
	
	/**
	 * SysDateTimePick32: with default state.
	 *		.text : Expiration Date:
	 * 		.class : SysDateTimePick32
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject sysDateTimePick32calendar2() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("sysDateTimePick32calendar2"));
	}
	/**
	 * SysDateTimePick32: with specific test context and state.
	 *		.text : Expiration Date:
	 * 		.class : SysDateTimePick32
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject sysDateTimePick32calendar2(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("sysDateTimePick32calendar2"), anchor, flags);
	}
	
	/**
	 * SysMonthCal32: with default state.
	 *		.class : SysMonthCal32
	 * 		.name : 
	 * 		.classIndex : null
	 */
	protected TopLevelSubitemTestObject sysMonthCal32calendar() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("sysMonthCal32calendar"));
	}
	/**
	 * SysMonthCal32: with specific test context and state.
	 *		.class : SysMonthCal32
	 * 		.name : 
	 * 		.classIndex : null
	 */
	protected TopLevelSubitemTestObject sysMonthCal32calendar(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("sysMonthCal32calendar"), anchor, flags);
	}
	
	

	protected Script1Helper()
	{
		setScriptName("TestScripts.Temp.Script1");
	}
	
}

